In [6]:
 #Numpy
 import numpy as np

In [9]:
a = [1,2,3,4]
b = [2,3,4,5]
ab = []
for i in range(0,len(a)):
   ab.append(a[i]*b[i])
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
a*b 


array([ 2,  6, 12, 20])

In [16]:
np.array([1,2,3,4,5,6])
np.zeros(10, dtype=int)
np.random.randint(0,10,size=10)
np.random.normal(10,4,(3,4))


array([[ 6.62345487,  9.81648827,  5.75110892,  8.54075706],
       [ 8.23678564,  6.09262643, 13.00893825,  8.01619049],
       [10.00361579,  4.472659  , 10.83389447, 15.78974083]])

In [21]:
#ndim : boyut yapısı
#shape: boyut bilgisi
#size: toplam eleman sayısı
#dtype : array veri tipi
a = np.random.randint(10,size=5)
a.ndim
a.size
a.dtype


dtype('int32')

In [25]:
np.random.randint(1,10,size=9)
np.random.randint(1,10,size=9).reshape(3,3)

ar = np.random.randint(1,10,size=9)
ar.reshape(3,3)



array([[8, 2, 3],
       [4, 3, 9],
       [6, 2, 6]], dtype=int32)

In [32]:
a = np.random.randint(10,size=10)
a[0]
a[0:5]
m=np.random.randint(10,size=(3,5))
m[0,0]
m[1,1]
m[:,0]



array([0, 2, 9], dtype=int32)

In [37]:
#fancy index
v = np.arange(0,30,3)
v[1]
v[4]
catch = [1,2,3]
v[catch]

array([3, 6, 9])